#%RAML 1.0 Trait
usage: Apply this trait to a GET method that supports pagination.
queryParameters:
  offset:
    type: integer
    required: false
    default: 0
    minimum: 0
    description: The `offset` parameter specifies the first entry to return from a collection.
  limit:
    type: integer
    required: false
    minimum: 1
    maximum: 1000
    description: The `limit` parameter restricts the number of entries returned.